# -*- coding: utf-8 -*-
"""New_York_Airbnb_Evilafo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNQ6xx_Q7EIEQTu0vPNrcRQN2UYf4svU

# Analyse descriptive du jeu de données de **Airbnb**.

### Importation des bibliothèques
"""

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style = "darkgrid")

"""### Chargement des données

Extraction des données à partir de google drive
"""

df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vS7x-_N9qhvDUXTxbsK1woTJwKPNXSsmu953-8cOHkoxSbgJtBmUgmG0E2tFwDCAT2eXKIlZA-omdVq/pub?gid=202319293&single=true&output=csv")
df.head()

"""### Exploration des données et visualisation

Explorons les données pour reconnaître les différentes relation entre l'ensemble de données.

# 1. Etudions la correlation à travers une fonction heatmap
"""

corr = df.corr(method='pearson')
plt.figure(figsize=(10,10))
sns.heatmap(corr, annot=True)

"""Il y'a une corrélation négative entre le commentaire et le nombre de nuités.

# 2. Les quartiers les plus sollicités
"""

df.neighbourhood_group.value_counts()

plt.figure(figsize=(13,7))
plt.title("Quartiers")
g = plt.pie(df.neighbourhood_group.value_counts(), labels=df.neighbourhood_group.value_counts().index,autopct='%1.1f%%', startangle=180)
plt.show()

"""Le graphique nous montre que les quartiers les plus sollicités sont Manhattan et Brooklyn.

Carte du groupe de voisinage
"""

plot_dims=(12,8)
plt.figure(figsize=plot_dims)
sns.scatterplot(df.longitude,df.latitude,hue=df.neighbourhood_group)
plt.show()

df.info()

"""Suppression des doublons, des colonnes inutiles."""

columns=['id','host_id','name','host_name','last_review','calculated_host_listings_count']
df=df.drop(columns,axis=1)
df.isnull().sum()

"""# 3.L'impact du prix sur les réservations par quartier.
### Répartition des prix groupe de quartier
"""

plt.figure(figsize=(13,7))
ax=df[df.price<600].plot(kind='scatter', x='longitude',y='latitude',label='Disponibilité',c='price',cmap=plt.get_cmap('jet'),colorbar=True,alpha=0.4)
ax.legend()
plt.title("Carte de répartition des prix")
plt.show()

plt.figure(figsize=(13,7))
plt.title("Répartition des prix par groupe de quartier")
sns.boxplot(y="price",x ='neighbourhood_group' ,data = df[df.price<600])
plt.show()

"""Manhattan a le prix le plus élevé avec environ 140 $ en prix moyen, suivi de Brooklyn avec 90 $ par nuit.
Queens, Staten Island et le Bronx sont les moins cher.
"""

df.corr()

"""### 4. Types de logements sont les plus plébiscités"""

plt.figure(figsize=(13,7))
plt.title("Type de logement")
sns.countplot(df.room_type, palette="muted")
fig = plt.gcf()
plt.show()

"""### Types de logements les plus plébiscités par quartier"""

plt.title("Types de logements les plus plébiscités par quartier")
sns.countplot(df.neighbourhood_group,hue=df.room_type, palette="muted")
plt.show()

"""Le graphique montre que les logements les plus plébiscités sont à Manhattan, tandis que les chambres privées et les appartements près de Brooklyn sont presque égaux."""